apache-websocket: add depend on pbzip2-native
This fixes the build failure:

ERROR: apache-websocket-0.1.1-r0 do_install_source: Failed to
archive (...) /bin/sh: pbzip2: command not found

Signed-off-by: Ioan-Adrian Ratiu <adrian.ratiu@ni.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
(cherry picked from commit 3a407c0cbcca10c7719f39ec0441c9d91deb5ab6)
(backported from origin/master into krogoth based branch)