mozjs: HACK: Remove $(prefix)/lib rpath-link entry
Mozilla binaries generally expect to link against shared libraries
located at relative paths in the install, i.e. libraries located at
../../dist/lib relative to the binary itself. This is accomplished
through -rpath-link settings in the link. This is controlled by the
MOZ_FIX_LINK_PATHS make variable which presently defaults to

MOZ_FIX_LINK_PATHS='-Wl,-rpath-link,$(LIBXUL_DIST)/bin -Wl,-rpath-link,$(prefix)/lib'

i.e., the dynamic linker searched for dependencies at "../../dist/bin"
and "/usr/lib" before the rest of the library search paths.

For reasons wholly mystifying to me, the build-time linker is *also*
checking these paths, *and* is ignoring the sysroot configuration. This
causes the build to fail when all of the following apply:

- The host has underwent /usr unification (i.e. /usr/lib symlinks to
  /lib). This means that /usr/lib/librt.so exists.
- The cross target is the same architecture as the host, i.e.
  x86_64->x86_64
- The host and target glibc versions differ in such a way that breaks
  the internal API between librt.so and libc.so. (archlinux users, this
  means you)
- You are building with a default $prefix (i.e. /usr).

In this case, the mozjs build fails with the following error:

/usr/lib/librt.so.1: undefined reference to `__shm_directory@GLIBC_PRIVATE'

I cannot find a great reason for why the $(prefix)/lib entry exists.
I'm not aware of any Mozilla shared libraries that install in
$(prefix)/lib instead of $(LIBXUL_DIST)/lib, and as long as mozjs is
never installed in a non-default prefix, /usr/lib is going to get
checked at runtime anyway.

So, until I get to the bottom of why the sysroot setting is failing so
badly, work around this build failure by deleting the rpath-link entry
entirely.

Signed-off-by: Richard Tollerton <rich.tollerton@ni.com>
(cherry picked from commit f46632c776d533e775c67a02804a03a8e6cfb20f)