ade: Fix install paths in multilib builds
Fixes
ERROR: ade-0.1.1f-r0 do_package: QA Issue: ade: Files/directories were installed but not shipped in any package:
  /usr/lib
  /usr/lib/libade.a

Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit b822b64aeb4d5c54c1f493cabc9011d741293439)
Signed-off-by: Joe Hershberger <joe.hershberger@ni.com>