fio: Upgrade to 3.7
* Licence-Update:
  Address update in COPYING
* Add patch 0001-update-the-interpreter-paths.patch
  and add python and bash to RDEPENDS_${PN} to fix
  below QA issues:
  ERROR: fio-3.7-r0 do_package_qa: QA Issue: /usr/bin/fiologparser.py contained in package fio requires /usr/bin/python2.7, but no providers found in RDEPENDS_fio? [file-rdeps]
  ERROR: fio-3.7-r0 do_package_qa: QA Issue: /usr/bin/genfio contained in package fio requires /usr/bin/bash, but no providers found in RDEPENDS_fio? [file-rdeps]

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>