efivar: backport upstream fixes
This is a combination of 5 commits fixing the efivar build in Krogoth.
These comits should be removed when upgrading post-krogoth, they are
contained in master.

Signed-off-by: Ioan-Adrian Ratiu <adi@adirat.com>
(Backported from origin/master)
efivar: update to 0.23

Upstream removed the use of the nvme headers completely,
so no more conflicts. Also drop gcc options patch, ubuntu
12.04 is too old to support in meta-oe/master.

Signed-off-by: Koen Kooi <koen.kooi@linaro.org>
Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
(cherry picked from commit 2ab67c55ce49a8fdbbae11bf6f98ded7d57cadf5)

efibootmgr: update and unblacklist

Also fix style issues.

Signed-off-by: Koen Kooi <koen.kooi@linaro.org>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
(cherry picked from commit 53226d6926b9d43f862b03d3010b302c4b9bbbf8)

efivar: fix do_install failed

It fixes efivar.pc not found:
...
| install -d -m 755 efivar/0.23-r0/image/usr/lib/pkgconfig/
| install -m 644 efivar.pc efivar/0.23-r0/image/usr/lib/pkgconfig/
;  install -m 644 efiboot.pc efivar/0.23-r0/image/usr/lib/pkgconfig/
;
| install: cannot stat 'efivar.pc': No such file or directory
| install: cannot stat 'efiboot.pc': No such file or directory
| make[1]: *** [install] Error 1
| make[1]: Leaving directory `efivar/0.23-r0/git/src'
| make: *** [install] Error 2
| ERROR: oe_runmake failed
...

Also sync with latest upstream

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
(cherry picked from commit 78d9701300ecb69adff52d8372e28423127cae7a)

efibootmgr: sync with upstream while efivar upgraded to 0.23

Sync with upstream to have the following fix:
...
commit 53aa9cdf7f0746f91f39521d020b024103041384
Author: Peter Jones <pjones@redhat.com>
Date:   Thu Mar 3 09:50:03 2016 -0500

    Explicitly pass a mode to efi_set_variable() in all cases.

    We'll have to do this for efivar-0.24 .

    Signed-off-by: Peter Jones <pjones@redhat.com>
...

It fixed compile failure:
...
efibootmgr.c: In function 'make_boot_var':
efibootmgr.c:305:7: error: too few arguments to function 'efi_set_variable'
  rc = efi_set_variable(boot->guid, boot->name, boot->data,
       ^
...

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
(cherry picked from commit b8cb1a131eed77476a25852de0c026c6c560125b)

efivar: fix unknown option while gold linker used

- Use '-fPIC' to replace 'PIC';

- Use 'pie' to replace 'PIE'

- Remove unknown '--add-needed'

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
(cherry picked from commit ad32a733bb62d5999f879b923a11d4c1e4c309df)