xfsprogs: Fix host contamination
Currently, the following symbolic links point to the host:
$ cd xfsprogs/4.18.0-r0/image
$ find . -type l -iname "lib*" -ls
./usr/lib/libhandle.so -> /lib/libhandle.so
./lib/libhandle.a -> /usr/lib/libhandle.a

This causes a build failure if the files already exist on the host:
ERROR: xfsprogs-4.18.0-r0 do_package_write_rpm: Function failed: BUILDSPEC
...
| NOTE: Creating RPM package for xfsprogs-fsck
| NOTE: Creating RPM package for xfsprogs-mkfs
| NOTE: Creating RPM package for xfsprogs-repair
| NOTE: Creating RPM package for libhandle1
| NOTE: Creating RPM package for xfsprogs-dbg
| NOTE: Creating RPM package for xfsprogs-staticdev
| NOTE: Creating RPM package for libhandle1
| NOTE: Creating RPM package for xfsprogs-doc
| NOTE: Not creating empty RPM package for xfsprogs-locale
| NOTE: Creating RPM package for xfsprogs
| NOTE: Creating RPM package for xfsprogs
| error: line 175: %package -n libhandle1: package libhandle1 already exists
...

Signed-off-by: Ovidiu Panait <ovidiu.panait@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>